services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - backend

  ingestion_service:
    build: ./ingestion_service
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - backend

  api_service:
    build:
      context: ./api_service
    container_name: api_service
    ports:
      - "57385:5000"
    volumes:
      - ./api_service/app:/app/app
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - backend

  dashboard_service:
    build: ./dashboard_service
    ports:
      - "57385:5000"
    volumes:
      - ./dashboard_service:/app
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - backend

  worker_service:
    build: ./worker_service
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - backend

  crypto_ingestor:
    build: ./ingestion_service
    command: python crypto_ws_ingestor.py
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
    driver: bridge
